### PR TITLE
feat: added prettier and formatted the files

### PR DESCRIPTION
**Pull request by ashmit-coder**
**Description**

-  Added prettier to make code maintainable and formatted the existing files.
**Related issue(s)**

Resolves: #331

### CODE REVIEW

**Comment by ashmit-coder** [comment]
Hey @thulieblack @AceTheCreator if these changes look good I will add the github workflow as well!

**Comment by AceTheCreator** [comment]
@ashmit-coder, all of these changes are made by the prettier script, right?

**Comment by ashmit-coder** [comment]
> @ashmit-coder, all of these changes are made by the prettier script, right?

yes, in addition to adding the command for prettier in the package.json

**Comment by ashmit-coder** [comment]
Hey @AceTheCreator do take a look I have added the workflow as well. :)

**Review by AceTheCreator — COMMENTED** [review]
Do you mind adding a download icon in the button to make users know that it's a download button?

**Comment by AceTheCreator** [comment]
> Hey @AceTheCreator do take a look I have added the workflow as well. :)

I checked the file, and it looks pretty good. Did you test it?

**Comment by ashmit-coder** [comment]
> > Hey @AceTheCreator do take a look I have added the workflow as well. :)
> 
> I checked the file, and it looks pretty good. Did you test it? 

Yeah I did test it with act

**Comment by AceTheCreator** [comment]
@ashmit-coder can you please resolve the conflict in this pr ?

**Comment by ashmit-coder** [comment]
@AceTheCreator done

**Comment by AceTheCreator** [comment]
@ashmit-coder sorry i missed your reminder, can you resolve the current conflict too 🙏🏾

**Comment by ashmit-coder** [comment]
Hey @AceTheCreator done

**Comment by AceTheCreator** [comment]
> Hey @AceTheCreator done

I noticed in your changes that it seems prettier ran on the .github directory too. should we allow such?

**Comment by ashmit-coder** [comment]
> > Hey @AceTheCreator done
> 
> I noticed in your changes that it seems prettier ran on the .github directory too. should we allow such?

I mean thats your call, but i guess newly added scripts should also be formatted. If you want I will revert those changes and limit it to not enter .github

**Comment by AceTheCreator** [comment]
> > > Hey @AceTheCreator done
> > 
> > 
> > I noticed in your changes that it seems prettier ran on the .github directory too. should we allow such?
> 
> I mean thats your call, but i guess newly added scripts should also be formatted. If you want I will revert those changes and limit it to not enter .github

I guess you're right in terms of new scripts.

**Comment by AnimeshKumar923** [comment]
Hi @ashmit-coder @AceTheCreator :wave: 

I noticed that the workflow directory is also being affected by it. It is centrally managed from https://github.com/asyncapi/.github 
Whenever there is a change in the central repository, the whole `.github` file is pulled and replicated across every repository under AsyncAPI. When that happens it would revert these changes because there is no prettier formatting in that repository.

It may become a hassle in the future with repeated formatting whenever a someone uses the `prettier` extension and may create confusion.

I would suggest to exclude the `.github` repo from the prettier linting.

**Comment by ashmit-coder** [comment]
Hey @AceTheCreator I will close this Pr and add prettier to the `Next Lint PR` Cause version control is giving a lot of issues while changing the .github folder

**Comment by ashmit-coder** [comment]
@AnimeshKumar923 your views will be really helpfull here
https://github.com/asyncapi/conference-website/pull/307

**Comment by AnimeshKumar923** [comment]
> @AnimeshKumar923 your views will be really helpfull here #307

I'll take a look at it. @ashmit-coder :+1:

**Pull request closed without merging**
