### PR TITLE
feat: past editions module

### PR DESCRIPTION
**Pull request by RamGoel**
**Description**

This PR implements the past editions module for 2023 edition of conference.(as of now)

Whatever the events get added to `cities-list.json`. It will automatically create pages out of it.

- Automatic & manual scroll in speakers slider
- returns 404 if the year is not in archive. (e.g., 2022)
- Year wise title for pages (Image attached)
- Removed agenda as it might not be relevant for past editions.

https://github.com/asyncapi/conference-website/assets/71088429/80b65931-43eb-4e58-82c4-cac0c589a3f2

image

**Related Issues**

Fixes some part of #259

### CODE REVIEW

**Comment by RamGoel** [comment]
The `venue` card was wrapped inside `Link` which was redirecting the recorded talk button to redirect also on the venue link. Moved that link to cover the image area only, so we can place multiple links on card.

**Comment by thulieblack** [comment]
This is coming together nicely. @Mayaleeeee @AceTheCreator thoughts on the Past Editions Page?

**Comment by Mayaleeeee** [comment]
> This is coming together nicely. @Mayaleeeee @AceTheCreator thoughts on the Past Editions Page?

 
Thank you for mentioning me, @thulieblack. And @RamGoel, I appreciate the work you've done on this issue. 

Regarding issue #211, @Thehussayn has already created a low-fidelity design that relates somewhat to this issue. I'll review it soon and see how we can incorporate both designs. 

@RamGoel, we'll remove the pagination dots under the **" Speaker's "** section from the design above and replace them with **"View All Speakers."** However, we'll keep the animation intact. 

Also, please change 'Past editions' to 'Past Editions' and replace 2023 with **AACoT'23** in the dropdown. 

Finally, I will re-review the design and the #211 issue to figure out how to make it work.

**Comment by Mayaleeeee** [comment]
> Hi both of you, a lil busy these days at work. will possibly try to fix them by next week.
> 

Hi @RamGoel 
Is there any update on this?

**Comment by RamGoel** [comment]
> > Hi both of you, a lil busy these days at work. will possibly try to fix them by next week.
> 
> Hi @RamGoel Is there any update on this?

Hi @Mayaleeeee Just give me time of today. I'll push the requested changes.

**Comment by RamGoel** [comment]
Hi @Mayaleeeee A new page will open of click of `View All Speakers` or will show the complete list in that section only.

**Comment by RamGoel** [comment]
Hi @Mayaleeeee can you help with this?

**Comment by Mayaleeeee** [comment]
> Hi @Mayaleeeee can you help with this?

**Comment by RamGoel** [comment]
Hi @Mayaleeeee , are you back on desk?

**Comment by Mayaleeeee** [comment]
> > This is coming together nicely. @Mayaleeeee @AceTheCreator thoughts on the Past Editions Page?
> 
> Thank you for mentioning me, @thulieblack. And @RamGoel, I appreciate the work you've done on this issue.
> 
> Regarding issue #211, @Thehussayn has already created a low-fidelity design that relates somewhat to this issue. I'll review it soon and see how we can incorporate both designs.
> 
> @RamGoel, we'll remove the pagination dots under the **" Speaker's "** section from the design above and replace them with **"View All Speakers."** However, we'll keep the animation intact.
> 
> Also, please change 'Past editions' to 'Past Editions' and replace 2023 with **AACoT'23** in the dropdown.
> 
> Finally, I will re-review the design and the #211 issue to figure out how to make it work.

Thanks @RamGoel. I have reviewed it, but you still need to make the changes we discussed here.

**Comment by Mayaleeeee** [comment]
> Hi @Mayaleeeee , are you back on desk?

Or is there a new update on it you'd like me to check?

**Comment by RamGoel** [comment]
> Hi @Mayaleeeee A new page will open of click of `View All Speakers` or will show the complete list in that section only.

I wanted your opinion on this.

**Comment by Mayaleeeee** [comment]
> > Hi @Mayaleeeee A new page will open of click of `View All Speakers` or will show the complete list in that section only.
> 
> I wanted your opinion on this.

Oh, great! Let's have a new page when users click on '**View All Speakers**' for the 2023 conference.

**Comment by RamGoel** [comment]
@Mayaleeeee I have implemented the new page for speakers inside the editions route, url goes like this `/editions/[year]/speakers`. 

The design of the editions page also has been updated after merging changes that @AceTheCreator made in #263 . You can check [this](https://deploy-preview-260--peaceful-ramanujan-288045.netlify.app/editions/2023/speakers) for latest preview

**Comment by thulieblack** [comment]
Sorry for jumping in late to the discussion.

But this won't be necessary anymore, @RamGoel, since all the conference pages are archived.

What you can work on now is to create a new page on the current website, "Past Editions," and add the previous conference websites.

here are the links to each:

1. 2023 - https://conference.2023.asyncapi.com/
2. 2022 -  https://conference.2022.asyncapi.com/
3. 2021 - https://conference.2021.asyncapi.com/
4. 2020 - https://conference.2020.asyncapi.com/

**Comment by RamGoel** [comment]
Okay @thulieblack , got your point. Would you like me to add a dropdown on past editions for all years or cards for all years on a new page?

**Comment by thulieblack** [comment]
Cards seem interesting. Lets see what you come up with 😉

**Comment by Mayaleeeee** [comment]
> Cards seem interesting. Lets see what you come up with 😉

I agree as well. Let's see how it turns out.

**Comment by RamGoel** [comment]
@thulieblack @Mayaleeeee raised a new PR #265

**Pull request closed without merging**
