### PR TITLE
fix: ticket section render issue

### LINKED ISSUE #395: Fix the way the ticket section is being rendered
In the ticket section of the website, it would be helpful to display all tickets, including those that have ended. This way, users can easily see the full history of available tickets, even after the events have passed. It provides more transparency and context for visitors browsing the section.

### PR DESCRIPTION
**Pull request by toffee-k21**
**Description**

- fixes #395 
- fixed card rendering issue in the `Ticket` section
Screenshot 2024-10-28 190734

### CODE REVIEW

**Comment by toffee-k21** [comment]
> @toffee-k21 we should stick to using the existing ticket cards. We should list all the tickets and only enable the upcoming conference ticket(which should come first)

Hey @AceTheCreator, I've updated the Ticket section to show upcoming events first, followed by events ended. This functionality was already implemented

**Comment by AceTheCreator** [comment]
> > @toffee-k21 we should stick to using the existing ticket cards. We should list all the tickets and only enable the upcoming conference ticket(which should come first)
> 
> Hey @AceTheCreator, I've updated the Ticket section to show upcoming events first, followed by events ended. This functionality was already implemented

But i think cards shouldn't have background

**Comment by toffee-k21** [comment]
> But i think cards shouldn't have background

Hey @AceTheCreator , I have removed the background as you mentioned

**Comment by ashmit-coder** [comment]
> > But i think cards shouldn't have background
> 
> Hey @AceTheCreator , I have removed the background as you mentioned

Looks great @toffee-k21 . 
But don't you think the items in the second row shoud start from the middle. (The london UK ticket card)
cc: @AceTheCreator

**Comment by toffee-k21** [comment]
> Looks great @toffee-k21 . But don't you think the items in the second row shoud start from the middle? (The london UK ticket card) cc: @AceTheCreator

@AceTheCreator, I have fixed the alignment and made the cards align in the middle

**Review by AceTheCreator — COMMENTED** [review]
@toffee-k21 i think it'll look visually appealing if the list of tickets is rendered in a carousel layout. wyt?

**Comment by toffee-k21** [comment]
> @toffee-k21 i think it'll look visually appealing if the list of tickets is rendered in a carousel layout. wyt?

Great idea! Displaying tickets in this way will keep the layout compact, conserving vertical space and this will also improve readability

**Review by AceTheCreator — COMMENTED** [review]
@toffee-k21 why are you not using the slider component we already have in code?

**Review by ashmit-coder — CHANGES_REQUESTED** [review]
Could you please demonstrate with a video how the component would look when the carousal effect is been applied.

**Comment by toffee-k21** [comment]
> @toffee-k21 why are you not using the slider component we already have in code?

Hey @AceTheCreator @ashmit-coder, I've implemented the card render section using the slider component. Let me know if there's anything you'd like to change!

**Comment by toffee-k21** [comment]
> Could you please demonstrate with a video how the component would look when the carousal effect is been applied.

I have raised a new PR #478 that will resolve this issue

**Pull request closed without merging**
