### PR TITLE
feat: past editions page

### PR DESCRIPTION
**Pull request by RamGoel**
**Description**
This PR adds a Past Editions page which can hold all the past editions of conference. 

For adding a new card to past editions page, just add the URL of archived conference into `config/editions.json`.

### CODE REVIEW

**Comment by RamGoel** [comment]
@thulieblack @Mayaleeeee Please have a look at this PR

**Comment by thulieblack** [comment]
image
It looks good, but let's replace the AACoT with **AsyncAPI Conf**, which might cause confusion with previous years

**Comment by RamGoel** [comment]
Done, made the change @thulieblack

**Review by thulieblack — APPROVED** [review]
Awesome thank you

**Comment by thulieblack** [comment]
@AceTheCreator please have a final look and merge please

**Comment by Mayaleeeee** [comment]
> @thulieblack @Mayaleeeee Please have a look at this PR 

Well done, @Ram. 

We can reduce the opacity of the purple background to make it more transparent and lessen the strong purple tone.

**Comment by AceTheCreator** [comment]
@RamGoel, I think we should be good to go once you add @Mayaleeeee suggested changes :)

**Comment by RamGoel** [comment]
hey @Mayaleeeee . Thanks for the feedback. I have made a change. Hopefully it looks good now. Let me know if you need any further change.

**Comment by RamGoel** [comment]
@Mayaleeeee please have a look when you're available.

**Comment by AceTheCreator** [comment]
@RamGoel I'd advise you resolve the merge conflict in your PR 🙏🏾

**Comment by AceTheCreator** [comment]
> @AceTheCreator done!

Awesome! Let's wait for @Mayaleeeee's review :)

**Comment by thulieblack** [comment]
@Mayaleeeee please review

**Comment by Mayaleeeee** [comment]
Thank you @RamGoel.  

1. Please kindly reduce this font and make it two lines instead of three; for example, `Past Events Of (this will be a line),`  then `AsyncAPI Conf will be another line.` It's way too big compared to the other ones on the website.

Screenshot 2024-03-20 071640


2. the cards are too small, and the vertical spacing is way too big compared to the horizontal spacing. Make the cards big, and give them the same vertical and horizontal spacing value.
Screenshot 2024-03-20 072150

**Comment by RamGoel** [comment]
sure @Mayaleeeee give me like half an hour. Doing this.

**Comment by Mayaleeeee** [comment]
> sure @Mayaleeeee give me like half an hour. Doing this.
> 

Alright.

**Comment by RamGoel** [comment]
image
Would you like this type of bg in text @Mayaleeeee . or I keep it as previous one only.

**Comment by Mayaleeeee** [comment]
> image
> Would you like this type of bg in text @Mayaleeeee . or I keep it as previous one only.
> 

I like it. 🥰

But let's reduce the font a little bit.

**Comment by RamGoel** [comment]
Please review it again @Mayaleeeee

**Comment by Mayaleeeee** [comment]
> Please review it again @Mayaleeeee 

Kindly send the image 🙏

**Comment by RamGoel** [comment]
@Mayaleeeee please have a look

**Comment by Mayaleeeee** [comment]
> @Mayaleeeee please have a look

Great work, @RamGoel! We're making progress, but we still need to fix some things. Don't worry, we'll get there together!

- The letter spacing between the `H E R E  C O M E S  T H E` is too much and looks weird; it should be `HERE COMES THE` 

We can also remove it because the sentence `Past Editions of AsyncAPI Conf` already communicates what we want.

Screenshot 2024-03-21 122647


- Let's try using the background colour in the image below for the cards; I think it looks better.
past edition


You can find the image in the Figma link [here](https://www.figma.com/file/sS5ofLRtuFqDGFvlNBurns/AACoT'23%2F24?type=design&node-id=1457%3A1002&mode=design&t=WSF3YfHUMebiyrt3-1).

**Comment by RamGoel** [comment]
@Mayaleeeee Busy in something. will do by EOD 22 March IST

**Comment by RamGoel** [comment]
image

How this looks @Mayaleeeee

**Comment by Mayaleeeee** [comment]
> image
> 
> How this looks @Mayaleeeee

Nice, but let's remove the effect at the end of the card.

**Comment by RamGoel** [comment]
image

**Comment by Mayaleeeee** [comment]
> Updated, Please check @Mayaleeeee 
> 
> image
> 

Thank you @RamGoel 

We can merge now cc @AceTheCreator @thulieblack

**Comment by thulieblack** [comment]
Congratulations @RamGoel 

@AceTheCreator please merge

**Comment by AceTheCreator** [comment]
LTGM!!! Welldone @RamGoel

**Pull request merged**
