### PR TITLE
chore: youtube link added in resource section (#425)

### LINKED ISSUE #425: Add link for London talks to the resources page
### Why do we need this improvement?

Add the YouTube link for the recorded London talks to the resources page

https://youtube.com/playlist?list=PLbi1gRlP7pig77jJD2ER9wfTxPSzBrLW5&si=YPmjUsj5mU6FpLhB

### 🚧 Breaking changes

No

### 👀 Have you checked for similar open issues?

- [X] I checked and didn't find a similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/asyncapi/.github/blob/master/CONTRIBUTING.md)

### Are you willing to work on this issue?

No, someone else can work on it.

### PR DESCRIPTION
**Pull request by toffee-k21**
**Description**

- fixes #425 
- Added link for London talks to the resources page

### CODE REVIEW

**Comment by thulieblack** [comment]
@toffee-k21, why did you remove the link to the London Slides?

You're suppose to add the London Talks as part of the resources don't remove whats currently there

**Comment by toffee-k21** [comment]
@thulieblack, I have added both London Talks and London Slides in the resource section

**Review by AceTheCreator — CHANGES_REQUESTED** [review]
Hey @toffee-k21, 

I think if the venue has recordings available, then we should include a button to the recordings on the venues page. something that says "watch recordings" 

wyt @thulieblack

**Comment by toffee-k21** [comment]
Hey @AceTheCreator @thulieblack, do you have recordings available for other talks as well? I would like to add them to the venue page.

**Comment by toffee-k21** [comment]
I have added the link to the venue page in such a way that recording links will only be displayed if they are available.
Screenshot 2024-10-19 004044
Screenshot 2024-10-19 004029

**Review by AceTheCreator — CHANGES_REQUESTED** [review]
The button should be larger than that 🤔

**Review by AceTheCreator — CHANGES_REQUESTED** [review]
This looks really awesome @toffee-k21, few suggestions

- i think the recording section should come after the agenda
- we should still have the button the heading, and the button should take us to the recordings section. wyt?

**Comment by toffee-k21** [comment]
Hi @AceTheCreator, thank you for your valuable suggestions. I have addressed the points you mentioned. Please let me know if any further changes are needed.

**Review by AceTheCreator — APPROVED** [review]
LGTM!

**Pull request merged**
