### PR TITLE
fix: added financial sponsor logo

### LINKED ISSUE #324: Add Gravitee Logo as Financial Sponsor
Add the Gravitee Logo on the conference website as our Finacial Sponsor.

Image

### PR DESCRIPTION
**Pull request by TenzDelek**
**Description**
Added Financial sponsor (gravitee.io) logo
image

**Related issue(s)**
Fixes #324

### CODE REVIEW

**Comment by thulieblack** [comment]
@TenzDelek can we follow the same font size for the **Financial Sponsor** same as **Host Sponsors**

image


And Also move the **Host Sponsors** heading to where I pointed

**Review by thulieblack — APPROVED** [review]

**Comment by AceTheCreator** [comment]
@thulieblack did you get this image from Gravitee themselves?

**Comment by thulieblack** [comment]
@AceTheCreator, the Gravitee logo I got is this one well, the one you see, I removed the white background to blend with the website design, but Im happy to revert it back

gravitee io_dark_blue_logo_720

**Review by Mayaleeeee — COMMENTED** [review]
Hello @TenzDelek 
Thanks for working on this.

Please change the logo and grab another one with a transparent background from this link: https://www.gravitee.io/branding

cc @thulieblack @AceTheCreator

**Comment by TenzDelek** [comment]
> Hello @TenzDelek Thanks for working on this.
> 
> Please change the logo and grab another one with a transparent background from this link: https://www.gravitee.io/branding
> 
> cc @thulieblack @AceTheCreator

have added logo from the official page 
c @Mayaleeeee  @AceTheCreator  @thulieblack

**Comment by Mayaleeeee** [comment]
> > Hello @TenzDelek Thanks for working on this.
> > 
> > Please change the logo and grab another one with a transparent background from this link: https://www.gravitee.io/branding
> > 
> > cc @thulieblack @AceTheCreator
> 
> have added logo from the official page 
> c @Mayaleeeee  @AceTheCreator  @thulieblack 

It looks good; it's just a tiny thing to do.
Reduce its size to be of the same size as the 'Apidays' logo.

**Comment by thulieblack** [comment]
Looks great,

 @Mayaleeeee , @AceTheCreator please approve so we can get this merged

**Review by Mayaleeeee — APPROVED** [review]
Thanks for your contribution, @TenzDelek

**Comment by AceTheCreator** [comment]
@thulieblack is Gravitee a financial sponsor for all the conferences?

**Comment by thulieblack** [comment]
yes @AceTheCreator

**Review by AceTheCreator — APPROVED** [review]
LGTM!

**Pull request merged**
