### PR TITLE
feat: added event gallery section

### PR DESCRIPTION
**Pull request by anuragnegi000**
**Description**
Created event gallery section, using plain css and tailwind

https://github.com/user-attachments/assets/7c59b0a4-40b1-4ca2-aae5-c822033e2453

- ...
- ...
- ...

**Related issue(s)**

#264

### CODE REVIEW

**Comment by Mayaleeeee** [comment]
Hi @anuragnegi000 

Thanks for your contribution! To align with our commit message conventions, could you please update your pull request title to use the correct format?
 
Please change it to: **feat: add a gallery section.**

Additionally, please include the demo video you mentioned in the previous issue in this pull request.

Thanks!

**Comment by ashmit-coder** [comment]
The gallery effects look great @anuragnegi000 but do add the nav and footer components to the page as well to make it aligned with the rest of the site.

**Comment by anuragnegi000** [comment]
> The gallery effects look great @anuragnegi000 but do add the nav and footer components to the page as well to make it aligned with the rest of the site.

please check the file changed as i haven't created any new page this section i have added it under Event and Host Sponsor

**Comment by AceTheCreator** [comment]
@anuragnegi000, i think a masonry layout will be more effective. wyt?

**Comment by anuragnegi000** [comment]
> ?

sure

**Comment by thulieblack** [comment]
@anuragnegi000 what's the status of this PR

**Comment by thulieblack** [comment]
@anuragnegi000 are you still working on this?

**Comment by ashmit-coder** [comment]
Lets close this pr @AceTheCreator  @thulieblack ?

**Comment by thulieblack** [comment]
Yes close it

**Pull request closed without merging**
