### PR TITLE
fix: misalignment in heading (#415)

### LINKED ISSUE #415: [BUG]  Misalignment in 'About The Event', 'Speakers', and 'Tickets' sections
### Describe the bug.

The headings for 'About The Event', 'Speakers', and 'Tickets' sections are misaligned. The blue line and text for these section headers are not consistently positioned across the page and multiple dimensions

### Expected behavior

All section headers ('About The Event', 'Speakers', 'Tickets') should be aligned consistently 

### Screenshots

scrnli_J5jrEkQo3wfOqe
scrnli_pzg9GXFNLWfN59
scrnli_wZue3xfknwfLf4

### How to Reproduce

Navigate to the conference website
Scroll through the page to view the 'About The Event', 'Speakers', and 'Tickets' sections

### 🥦 Browser

Google Chrome

### 👀 Have you checked for similar open issues?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/asyncapi/.github/blob/master/CONTRIBUTING.md)

### Are you willing to work on this issue ?

Yes I am willing to submit a PR!

### PR DESCRIPTION
**Pull request by toffee-k21**
**Description**

- fixes #415 
- this PR will close the issue of misalignment in 'About The Event', 'Speakers', and 'Tickets' sections 

Screenshot 2024-10-17 165118

Screenshot 2024-10-17 165130

### CODE REVIEW

**Comment by AceTheCreator** [comment]
@Manancode  does this fix the issue you proposed?

**Comment by Manancode** [comment]
Yes sir @AceTheCreator . Checked locally and it fixes the issue I proposed

**Review by AceTheCreator — APPROVED** [review]
LGTM

**Pull request merged**
