### PR TITLE
feat: add ashmit-coder as maintainer

### PR DESCRIPTION
**Pull request by ashmit-coder**
**Description**
Adding @ashmit-coder in the codeowners.

### CODE REVIEW

**Review by Mayaleeeee — APPROVED** [review]

**Review by AceTheCreator — COMMENTED** [review]
@thulieblack @Mayaleeeee your approvals are required

**Comment by AceTheCreator** [comment]
@thulieblack reminder

**Comment by thulieblack** [comment]
Welcome to the maintainers side @ashmit-coder some work ahead 😈

**Comment by ashmit-coder** [comment]
> Welcome to the maintainers side @ashmit-coder some work ahead 😈

😬 thankss! @AceTheCreator @thulieblack and @Mayaleeeee 😂

**Pull request merged**
