### PR TITLE
fix: darken the background image of the card

### LINKED ISSUE #266: Card text is unreadable
- The texts on the location images are difficult to read.

h

Instead, we could have something like the one below; you can check it in the Figma file [here](https://www.figma.com/file/sS5ofLRtuFqDGFvlNBurns/AsyncAPI-Conference-on-Tour'23%2FAACoT?type=design&node-id=1457%3A1002&mode=design&t=MkiKZWZHWuXJFlDO-1).
Paris

### PR DESCRIPTION
**Pull request by Gmin2**
fixes #266 

**Description**

image

### CODE REVIEW

**Comment by AceTheCreator** [comment]
@utnim2 Thanks for the contribution, can you make it similar to the one suggested In the issue?

**Comment by utnim2** [comment]
> @utnim2 Thanks for the contribution, can you make it similar to the one suggested In the issue?




done

**Comment by AceTheCreator** [comment]
@Mayaleeeee Is this fine by you?

**Comment by Mayaleeeee** [comment]
> @Mayaleeeee Is this fine by you?

Thank you, @AceTheCreator. Also, thank you to @utnim2 for your contribution.

@utnim2, please use the design in the Figma file [here](https://www.figma.com/file/sS5ofLRtuFqDGFvlNBurns/AsyncAPI-Conference-on-Tour'23%2FAACoT?type=design&node-id=1457%3A1002&mode=design&t=MkiKZWZHWuXJFlDO-1) to improve your work. Your current work is okay, but it can be better if you follow the same spacing and color used.

**Comment by thulieblack** [comment]
@utnim2 you still working on this?

**Comment by utnim2** [comment]
> @utnim2 you still working on this?
> 

Yes @thulieblack was out of town for a bit,now working on it

**Comment by thulieblack** [comment]
Awesome

**Comment by Mayaleeeee** [comment]
Well done, @utnim2. 

Do you have any updates?

**Comment by utnim2** [comment]
> Well done, @utnim2.
> 
> Do you have any updates?

Pushed the changes @Mayaleeeee

**Comment by thulieblack** [comment]
@Gmin2 please resolve the conflicts

**Comment by thulieblack** [comment]
@Gmin2 are you still intereseted in working on this issue?

**Comment by Gmin2** [comment]
Let others take this up

**Pull request closed without merging**
