### PR TITLE
feat: venue clickable address links

### LINKED ISSUE #202: venues addresses to be clickable links that take you you google map location
like in title, basically every venua has a string with address

would be nice if this is a link to google maps to a pin to location

long term even nicer would be to have embedded map, but I guess separate issue for discussion

### PR DESCRIPTION
**Pull request by Mithilesh-create**
**Description**
Venue addresses are now clickable that opens location in new tab.

image

**Related issue(s)**
closes #202

### CODE REVIEW

**Comment by AceTheCreator** [comment]
@Mithilesh-create looks like you have checks failing :)

**Comment by Mithilesh-create** [comment]
> @Mithilesh-create looks like you have checks failing :)

Now I have fixed failing changes please merge the code .

**Comment by AceTheCreator** [comment]
@Mithilesh-create can you make the address underlined? That will make it look clickable

**Comment by AceTheCreator** [comment]
Sorry, I have to fix this PR cuz the issue has been resolved in the updated version

**Pull request closed without merging**
