### PR TITLE
fix: resources added for Helsinki

### LINKED ISSUE #325: Add Helsinki Slides Link Resources
Add the Speaker Slides Resources Link under the Helsinki Page

https://drive.google.com/drive/folders/1nY7dZF8WFXZ3r2rCWJDDoT2C_GMfQJMV?usp=drive_link

### PR DESCRIPTION
**Pull request by TenzDelek**
**Description**
resources added for Helsinki
image

**Related issue(s)**
Fixes #325

### CODE REVIEW

**Comment by thulieblack** [comment]
@TenzDelek, why not replicate what we did last year and something similar to this

image

https://conference.2023.asyncapi.com/

**Comment by TenzDelek** [comment]
> @TenzDelek, why not replicate what we did last year and something similar to this
> 
> 
> 
> image
> 
> 
> 
> https://conference.2023.asyncapi.com/

@thulieblack sure, will implement that

**Comment by Mayaleeeee** [comment]
> @TenzDelek, why not replicate what we did last year and something similar to this
> 
> image
> 
> https://conference.2023.asyncapi.com/

I prefer this as well.

**Review by Mayaleeeee — COMMENTED** [review]
➕1 on the suggestion Thulie made about the resources.

**Comment by ashmit-coder** [comment]
Hey @TenzDelek can you make it centered does not look good when there is just one element in the drop down.
Screenshot from 2024-06-08 10-22-51


Also fix the top and bottom paddings to make them similar

**Comment by TenzDelek** [comment]
> Hey @TenzDelek can you make it centered does not look good when there is just one element in the drop down.
> 
> Screenshot from 2024-06-08 10-22-51
> 
> 

Sure, have my nimcet exam today, will start the changes from tomorrow 👍

**Comment by TenzDelek** [comment]
> Hey @TenzDelek can you make it centered does not look good when there is just one element in the drop down. Screenshot from 2024-06-08 10-22-51

@ashmit-coder  have done the centering :)

**Review by ashmit-coder — APPROVED** [review]
LGTM!

**Review by thulieblack — APPROVED** [review]
LGTM

**Review by AceTheCreator — CHANGES_REQUESTED** [review]
@TenzDelek i think you should take a look at the alignment on the venue menu, you've probably messed with he alignment.

**Comment by TenzDelek** [comment]
> @TenzDelek i think you should take a look at the alignment on the venue menu, you've probably messed with he alignment.

hmm.. interesting, the plan was to move the items to the center as it doesn't look great when there is only one item as suggested by @ashmit-coder . should i write a logic for it or make it back to default layout?? 
cc @AceTheCreator

**Comment by AceTheCreator** [comment]
> > @TenzDelek i think you should take a look at the alignment on the venue menu, you've probably messed with he alignment.
> 
> hmm.. interesting, the plan was to move the items to the center as it doesn't look great when there is only one item as suggested by @ashmit-coder . should i write a logic for it or make it back to default layout?? cc @AceTheCreator

Yes, please

**Comment by TenzDelek** [comment]
> > > @TenzDelek i think you should take a look at the alignment on the venue menu, you've probably messed with he alignment.
> > 
> > 
> > hmm.. interesting, the plan was to move the items to the center as it doesn't look great when there is only one item as suggested by @ashmit-coder . should i write a logic for it or make it back to default layout?? cc @AceTheCreator
> 
> Yes, please

yes for implementing a further function or making it back to default? :),  from my perspective, i think reverting it back to the default sounds better as there will be further resources added in the near future.

**Comment by thulieblack** [comment]
@TenzDelek whats the status here?

**Comment by TenzDelek** [comment]
> @TenzDelek whats the status here?

@thulieblack  done :)

**Comment by thulieblack** [comment]
you have some conflicts you need to resolve first

**Comment by thulieblack** [comment]
@AceTheCreator check the changes

**Comment by AceTheCreator** [comment]
@TenzDelek, i noticed a bug. when I hover on the resources tab, the venue dropdown gets activated. Can you look into that?

**Comment by TenzDelek** [comment]
@AceTheCreator  this should fix it :)

**Review by ashmit-coder — CHANGES_REQUESTED** [review]
Hey @TenzDelek the dropdown options have became unclickable, due to changes.

It has affected the venues section as well, ptal.

**Comment by ashmit-coder** [comment]
https://github.com/asyncapi/conference-website/assets/69006513/9d595844-a152-4b21-a2c6-40b4a6e73780
Heres a video to refrence what am requesting @TenzDelek

**Comment by AceTheCreator** [comment]
@TenzDelek can you look into rectifying the issue with your PR?

**Comment by TenzDelek** [comment]
@ashmit-coder  @AceTheCreator  Done with the Change :)

**Review by ashmit-coder — APPROVED** [review]
LGTM!

**Pull request merged**
