### PR TITLE
feat: add google analytics configuration

### LINKED ISSUE #95: We need to integrate google analytics as we had on previous conf website
Tracking id is `UA-109278936-3`

but like in case of main website I think we need to enable GA4 because old GA will go away pretty soon afaik.

so yeah, whoever works on it, see how it is done for AsyncAPI website, and lemme know if I need to do something in GA4

### PR DESCRIPTION
**Pull request by sambhavgupta0705**
**Description**
- added the google analytics functionality to the conference website 

**Related issue(s)**

Resolves #95

### CODE REVIEW

**Comment by sambhavgupta0705** [comment]
cc @derberg @AceTheCreator

**Review by derberg — COMMENTED** [review]
Nice work @sambhavgupta0705 

I've now setup GA4 and configured the tag to make sure all is fine -> and it works 🚀 

In the meantime please remove `yarn.lock` from this PR. Having `package.lock.json` is enough.

Also update description from `#95` to `Resolves #95` as this way after merging PR related issue will automatically be closed

**Comment by sambhavgupta0705** [comment]
@derberg thanks for reviewing it.
I have removed yarn.lock and edited the description

**Review by derberg — APPROVED** [review]
@sambhavgupta0705 thanks so much for that contribution 🙇🏼 

@AceTheCreator wanna have a look before we merge this one?

**Comment by AceTheCreator** [comment]
LGTM @derberg 

Welldone @sambhavgupta0705

**Comment by sambhavgupta0705** [comment]
Thanks Ace

**Pull request merged**
