### PR TITLE
feat: adds hover effect

### LINKED ISSUE #170: Implement visual states for images on location cards (hovered and clicked)
#### Reason/Context
There is no effect when users hover or click on the location cards. 

#### Description
Implement visual states for images to improve user experience. This enhancement will help users understand what's happening by elevating the cards when hovered over and appropriately responding when clicked on. 

Here's a short recording  of how the section looks:
 
[331feb3d-22c6-434b-9c03-481a09148ab6.webm](https://github.com/asyncapi/conference-website/assets/105395613/2fbd4a17-8add-49f5-a8d9-346130a782b6)

### PR DESCRIPTION
**Pull request by SoNiC-HeRE**
**Description**

- Before:

[Implement visual states for images on location cards (hovered and clicked) · Issue #170 · asyncapi_conference-website.webm](https://github.com/asyncapi/conference-website/assets/96797205/fa6c348d-f648-4f0b-b52b-18c35498bb55)

- After:

https://github.com/asyncapi/conference-website/assets/96797205/245e5a5a-9c24-4fcd-aab0-435b16fc2a38

Kept the animation minimalistic and not flashy so in to blend with the theme and for a good user experience
**Related issue(s)**
Fixes #170

### CODE REVIEW

**Comment by SoNiC-HeRE** [comment]
@Mayaleeeee please let me know if any changes are required

**Comment by Mayaleeeee** [comment]
> @Mayaleeeee wyt?

I love it @SoNiC-HeRE, thank you!
However, I noticed there is no interaction on the mobile version. Did you also see that @AceTheCreator, or is it just from me?

**Comment by AceTheCreator** [comment]
> > @Mayaleeeee wyt?
> 
> I love it @SoNiC-HeRE, thank you! However, I noticed there is no interaction on the mobile version. Did you also see that @AceTheCreator, or is it just from me?

yeah, I believe it's cuz @SoNiC-HeRE is only using the hover effect

**Comment by SoNiC-HeRE** [comment]
@AceTheCreator @Mayaleeeee Is it good to go or any changes are required?

**Comment by AceTheCreator** [comment]
> @AceTheCreator @Mayaleeeee Is it good to go or any changes are required?

LGTM! @Mayaleeeee your thoughts?

**Comment by Mayaleeeee** [comment]
> > @AceTheCreator @Mayaleeeee Is it good to go, or any changes are required?
> 
> LGTM! @Mayaleeeee your thoughts?

Looks good; we are good to go, @AceTheCreator.
Thanks @SoNiC-HeRE 

However, I am not seeing the same interaction for the mobile version @SoNiC-HeRE.

**Comment by SoNiC-HeRE** [comment]
> > > @AceTheCreator @Mayaleeeee Is it good to go, or any changes are required?
> > 
> > 
> > LGTM! @Mayaleeeee your thoughts?
> 
> Looks good; we are good to go, @AceTheCreator. Thanks @SoNiC-HeRE
> 
> However, I am not seeing the same interaction for the mobile version @SoNiC-HeRE.

Yes, cause ```::hover```  pseudo-class doesn't work on touch displays. See https://developer.mozilla.org/en-US/docs/Web/CSS/:hover

**Comment by Mayaleeeee** [comment]
> > > > @AceTheCreator @Mayaleeeee Is it good to go, or any changes are required?
> > > 
> > > 
> > > LGTM! @Mayaleeeee your thoughts?
> > 
> > Looks good; we are good to go, @AceTheCreator. Thanks @SoNiC-HeRE
> > 
> > However, I am not seeing the same interaction for the mobile version @SoNiC-HeRE.
> 
> Yes, cause ```::hover```  pseudo-class doesn't work on touch displays. See https://developer.mozilla.org/en-US/docs/Web/CSS/:hover

We are good to go then @AceTheCreator

**Pull request merged**
