### PR TITLE
feat: added sponsors

### PR DESCRIPTION
**Pull request by AceTheCreator**
**Description**

- ...
- ...
- ...

**Related issue(s)**

### CODE REVIEW

**Comment by derberg** [comment]
these are 2 different level of sponsors, platinum and gold. It should be visible. Please have a look at https://conference.2021.asyncapi.com/ as reference. There are 2 sections, and gold sponsors have smaller logo

**Comment by derberg** [comment]
@AceTheCreator I don't get it? by label you mean header?

**Comment by derberg** [comment]
@AceTheCreator can I help you somehow?

**Comment by AceTheCreator** [comment]
@derberg sorry for the late response :( 

Updated the PR with what I suggested.

**Comment by derberg** [comment]
only one small thing @AceTheCreator 
I think it should be centered like the rest

**Comment by AceTheCreator** [comment]
@derberg make sense like this?

**Pull request merged**
