### PR TITLE
fix: all ticket types are rendered

### LINKED ISSUE #395: Fix the way the ticket section is being rendered
In the ticket section of the website, it would be helpful to display all tickets, including those that have ended. This way, users can easily see the full history of available tickets, even after the events have passed. It provides more transparency and context for visitors browsing the section.

### PR DESCRIPTION
**Pull request by NamanSriva**
fix: This PR fixes the ways tickets are being rendered. Earlier only upcoming tickets were rendered but now all the tickets including ended or upcoming are rendered and displayed some more info about tickets(description). Also improved the UI so that while hovering tickets do not overlap on each other.

Screenshot (94)

**Related issue(s)**
Fixes #395

### CODE REVIEW

**Comment by ashmit-coder** [comment]
Hey @NamanSriva the changes look good, could you just make it so that the active tickets are on top in the mobile view and others below it.

cc: @AceTheCreator , this looks way suitable to our design in my opinion.

**Comment by NamanSriva** [comment]
@ashmit-coder sure I'll do it ASAP

**Review by AceTheCreator — COMMENTED** [review]
Awesome changes @NamanSriva but wouldn't it be even better if tickets renders in carousel? 

Also disable/reduce the overlay effect onHover 

cc @ashmit-coder

**Comment by ashmit-coder** [comment]
> Awesome changes @NamanSriva but wouldn't it be even better if tickets renders in carousel?
> 
> Also disable/reduce the overlay effect onHover


I do agree on the overlay effect.

about the carousel, ig it will make sense considering uniformity. So yeah a carousel sounds good , but just in desktop view. 
I think for mobile view plane linear scroll works better.

**Comment by ashmit-coder** [comment]
Hey @NamanSriva why did you close the pr?

**Comment by NamanSriva** [comment]
@ashmit-coder actually there was error in naming the branch and it failed some tests while doing commit.

**Comment by ashmit-coder** [comment]
> @ashmit-coder actually there was error in naming the branch and it failed some tests while doing commit.

Okay so you reopening another pr?

**Pull request closed without merging**
