### PR TITLE
fix: correction made on speaker cards

### PR DESCRIPTION
**Pull request by Mayaleeeee**
Correction made on speakers card #117
@derberg @alequetzalli 
Good morning and happy new week to you; please check; all typos have been fixed.

### CODE REVIEW

**Comment by derberg** [comment]
@alequetzalli I reviewed and I think it is ok. But let's make sure you review this time too 😅

**Comment by magicmatatjahu** [comment]
@Mayaleeeee `fix:` not `fixes:` 😄

**Comment by Mayaleeeee** [comment]
Yeahh😑😑🙈🙈😂😂
Thank you @magicmatatjahu

**Comment by alequetzalli** [comment]
> @alequetzalli I reviewed and I think it is ok. But let's make sure you review this time too 😅

It's a good thing I did, because you missed another error @derberg 😂😂😂 (Maya fixed it now, it's ok)

**Review by alequetzalli — APPROVED** [review]
🚢  🛳 🚢  🛳 🚢  🛳 🚢  🛳 🚢  🛳 🚢  🛳

**Comment by Mayaleeeee** [comment]
Thank you so much 🥰

**Comment by alequetzalli** [comment]
@Mayaleeeee you have to fix your PR title here too. It's `fix` not `fixes`.

**Comment by Mayaleeeee** [comment]
Thanks to this website, I now look like a liar 😭😭😭 I swear I made changes from my laptop as soon as @magicmatatjahu mentioned it yesterday, so I was shocked when I noticed it again this morning. I thought if Alejandra saw it again, she would probably start talking.

At this point, I'm hoping it's fixed.🤗🤗

**Comment by derberg** [comment]
@Mayaleeeee I changed it, it should be `fix:`

**Comment by Mayaleeeee** [comment]
Good morning @derberg 
I was so sure I changed it yesterday.

Why is it fix though?? Does it have anything to do with github???

**Comment by derberg** [comment]
yes, you changed, but to `fixes:`

Screenshot 2022-10-25 at 09 06 24

then you had it wrong, there was a comment from the bot explaining why your PR title is wrong, and what has to be fixed. It is related to https://www.conventionalcommits.org/en/v1.0.0/

**Comment by Mayaleeeee** [comment]
Ohhh
I get it now.

**Pull request merged**
