### PR TITLE
fix: resolved lint warnings

### LINKED ISSUE #328: [FEATURE] Resolve the existing Next.js lint issues
### Why do we need this improvement?

To improve the lint flow of the website and put proper checks in place.

**`NOTE`: **This is a breaking change hence, when you work on this make sure to not dirupt the functionality****

### How will this change help?

It will make better use of Next.js components and hence improve in website performance.

### Screenshots

Screenshot from 2024-04-09 10-50-05

### How could it be implemented/designed?

1. Lint the code using the `npm run lint` command. 
2. Resolve the warnings that occur in the terminal.
3. Resources to follow  https://nextjs.org/docs

### 🚧 Breaking changes

Yes

### 👀 Have you checked for similar open issues?

- [X] I checked and didn't find a similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/asyncapi/.github/blob/master/CONTRIBUTING.md)

### Are you willing to work on this issue?

No, someone else can work on it.

### Suppoerted issues

https://github.com/asyncapi/conference-website/issues/306

### Supported PR

https://github.com/asyncapi/conference-website/pull/307

### PR DESCRIPTION
**Pull request by SahilDahekar**
**Description**

- Fixed lint warning in ```stepThree.js``` & ```select.js``` files.

**Related issue(s)**

Fixes #328

### CODE REVIEW

**Review by AceTheCreator — CHANGES_REQUESTED** [review]
Do you mind sharing the screenshot of before and after your fix?

**Comment by SahilDahekar** [comment]
Here are before and after images :- 

Before : 
image

After :
image

**Comment by AceTheCreator** [comment]
@ashmit-coder your review is needed :)

**Comment by ashmit-coder** [comment]
> @ashmit-coder your review is needed :)

Hey @AceTheCreator waiting for this pr https://github.com/asyncapi/conference-website/pull/386 

So that the tests are ran on this pr, just to be sure all functionalities are working.

**Comment by SahilDahekar** [comment]
Hey @ashmit-coder , since PR #386 is merged can we proceed with this PR.

**Comment by ashmit-coder** [comment]
> Hey @ashmit-coder , since PR #386 is merged can we proceed with this PR.

Sure! Soon

**Review by ashmit-coder — APPROVED** [review]

**Comment by ashmit-coder** [comment]
hey @AceTheCreator ptal

**Comment by ashmit-coder** [comment]
@SahilDahekar could you confirm that there are no further warnings after the updation to the code.

**Comment by SahilDahekar** [comment]
No lint warnings @ashmit-coder 
image

**Review by AceTheCreator — APPROVED** [review]
LGTM!

**Pull request merged**
