### PR TITLE
fix: header sizing

### LINKED ISSUE #175: Change the font size used for the header on the Conference Website.
#### Reason/Context
The current font size is regular text, but it should be a header.

Screenshot 2023-08-28 203543

#### Description
Please increase the font size and make it bold. **Set the font size to 88x, line height to 80px, and letter spacing to -3, as** shown in the image below.

Screenshot 2023-08-28 210725

### PR DESCRIPTION
**Pull request by SoNiC-HeRE**
**Description**

- Made the font bold, increased text-size, line-height and letter-spacing
- Used available classes rather than going for custom css class

- Before:
263816058-a9c3d5c0-7b72-4b7b-aec6-6e1421610c62

- Applying custom-class as provided here 
https://github.com/asyncapi/conference-website/issues/175#issue-1870427927
Screenshot 2023-08-29 213909

- Applying Pre-Defined Class (Current):
Screenshot 2023-08-29 214027

Decided to stick with the last layout as it appears more clean but if required, I'd change it as suggested

**Related issue(s)**
Fixes #175

### CODE REVIEW

**Comment by SoNiC-HeRE** [comment]
@Mayaleeeee please let me know if any changes are required

**Comment by Mayaleeeee** [comment]
> @Mayaleeeee please let me know if any changes are required

Thank you @SoNiC-HeRE 
The second one looks good. cc @thulieblack @derberg @AceTheCreator

**Review by Mayaleeeee — APPROVED** [review]
Looks great.
Thank you @SoNiC-HeRE 

cc @thulieblack @AceTheCreator @derberg

**Comment by SoNiC-HeRE** [comment]
> @SoNiC-HeRE can you update the branch with the latest changes from master

sure

**Comment by SoNiC-HeRE** [comment]
@AceTheCreator please let me know if any more changes are required

**Comment by AceTheCreator** [comment]
> @AceTheCreator please let me know if any more changes are required

Noticed the heading size stays the same despite the screen size. I believe is should be smaller on mobile screen size. cc @Mayaleeeee

**Comment by Mayaleeeee** [comment]
> > @AceTheCreator please let me know if any more changes are required
> 
> Noticed the heading size stays the same despite the screen size. I believe is should be smaller on mobile screen size. cc @Mayaleeeee

Yeah, I just noticed that too, thanks @AceTheCreator 

@SoNiC-HeRE, please use **32px for the text, 38px for line height and -2% for letter spacing for the header size on mobile.**
Screenshot 2023-09-04 215311

This is how the mobile version looks like
Home-Mobile

**Comment by SoNiC-HeRE** [comment]
- Before:

image

- After:

mobile

**Comment by AceTheCreator** [comment]
LGTM! @Mayaleeeee wyt?

**Comment by Mayaleeeee** [comment]
> LGTM! @Mayaleeeee wyt?

Awesome 🤗🤗

**Pull request merged**
