### PR TITLE
fix: subscription button modified #217

### LINKED ISSUE #217: Inconsistent styling of the subscribe button on the conference website
#### Describe the bug
There is a bug in styling the "Subscribe" button on the conference website. It looks different from the other buttons on the site, causing issues with the size of the button and the spacing of the text inside it.  
  
Screenshot 2023-10-11 032035
 
 
#### Expected behavior
 Ensure the "Subscribe" button is styled consistently with other buttons on the website.

### PR DESCRIPTION
**Pull request by AyushmanSinghRajawat**
fixes #217 
hey, @asyncapi-bot  I have modified the subscription button by using the existing Button component so it will have same styling like other buttons in the app and i have also provided relevant top margin.
I had also updated caniuse-lite to it's latest version as otherwise it was not working.
I am new to open source and I enjoyed working on this issue, hope you like my solution.
Please let me know your thoughts and suggestions.

### CODE REVIEW

**Comment by AceTheCreator** [comment]
@Mayaleeeee what do you think?

**Comment by AyushmanSinghRajawat** [comment]
I think my solution modifies the subscription button to look exactly like other buttons in the project. If you have any feedback please let me know I will work on that.

**Comment by Mayaleeeee** [comment]
> @Mayaleeeee what do you think?

Thank you @AyushmanSinghRajawat 

It looks perfect on the web but is not well positioned on the mobile version.

It should be centre-aligned with the same length as the **"All"** button under the speakers' section @AyushmanSinghRajawat.
Screenshot 2023-10-12 232708

cc @AceTheCreator, I noticed that the buttons on the mobile version of the website are different in length. In particular, they should all be the same length as the "ALL" button under the speakers' section. Should I open a separate issue, or can we handle it under this PR?

**Comment by Mayaleeeee** [comment]
> I think my solution modifies the subscription button to look exactly like other buttons in the project. If you have any feedback, please let me know I will work on that.

Hi @AyushmanSinghRajawat, thank you for working on this. I have reviewed your work and provided my feedback.

**Comment by AyushmanSinghRajawat** [comment]
Thank you @Mayaleeeee  for reviewing my work, I can center-align the subscribe button with same length as "All" button. Should I also change the length of all buttons in mobile version? if yes, please let me know, i will make the changes ASAP.

**Comment by Mayaleeeee** [comment]
> Thank you @Mayaleeeee for reviewing my work, I can center-align the subscribe button with same length as "All" button. Should I also change the length of all buttons in mobile version? if yes, please let me know, i will make the changes ASAP.

Yes, please. You can do that.

wdy @AceTheCreator

**Comment by AceTheCreator** [comment]
> Thank you @Mayaleeeee for reviewing my work, I can center-align the subscribe button with same length as "All" button. Should I also change the length of all buttons in mobile version? if yes, please let me know, i will make the changes ASAP.

This should be in a different PR

**Comment by Mayaleeeee** [comment]
> > Thank you @Mayaleeeee for reviewing my work, I can center-align the subscribe button with same length as "All" button. Should I also change the length of all buttons in mobile version? if yes, please let me know, i will make the changes ASAP.
> 
> This should be in a different PR

@AyushmanSinghRajawat

**Comment by AyushmanSinghRajawat** [comment]
ok @AceTheCreator @Mayaleeeee , so for now i should just fix the subscribe button alignment and size, right? and can I raise a new issue for the new PR? I am new to open source so I truly appreciate any guidance from your side.

**Comment by Mayaleeeee** [comment]
> ok @AceTheCreator @Mayaleeeee , so for now i should just fix the subscribe button alignment and size, right? and can I raise a new issue for the new PR? I am new to open source so I truly appreciate any guidance from your side.

Yeah, adjust the alignment and size of the subscribe button in this PR

And submit another PR for fixing the sizing of all buttons in the mobile version. 

Please, feel free to reach out if you require any further assistance.

**Comment by AyushmanSinghRajawat** [comment]
image
I have fixed the alignment and size for the button please review my work and merge my PR.

**Comment by AceTheCreator** [comment]
@Mayaleeeee is this okay?

**Comment by Mayaleeeee** [comment]
> @Mayaleeeee is this okay?

Yes, boss.

Thank you @AyushmanSinghRajawat

**Comment by AyushmanSinghRajawat** [comment]
Kindly merge my PR.

**Comment by AyushmanSinghRajawat** [comment]
Hey @AceTheCreator I have updated this branch. You can merge this PR now.

**Comment by AyushmanSinghRajawat** [comment]
hey, @AceTheCreator kindly merge my PR.

**Comment by AyushmanSinghRajawat** [comment]
@AceTheCreator I have updated this branch and also removed changes from package-lock. You can merge my PR now.

**Pull request merged**
