### PR TITLE
feat: gallery section added

### LINKED ISSUE #264: Add Gallery Section to AACoT'24 Conference Website
#### Description
The section should include a button labeled 'Browse All' or 'See All', and 

- will have a header titled 'Our Events Gallery'.
- a button labeled 'Browse All', and 

When users click on the button, they should be directed to a 

- Google Drive folder with all the images, 
**Or**  to a 
- new page with cards displaying the location, year, and a 'View Gallery' button for each event.

 Since AACoT'23 was our first in-person conference, there will be three cards (for each of the locations) with a 'View Gallery' button that leads to a Google Drive folder.

#### Expected Behavior
Users should be able to easily browse through the gallery of images from past events by clicking on the 'Browse All' or 'See All' button.

#### Why we should have this
This feature will enhance the user experience by providing a visual representation of past events.

### PR DESCRIPTION
**Pull request by cybraia**
**Description**
Added past events photos gallery using a reactjs library. 
screenshot1
screenshot2

**Related issue(s)**
Resolves #264

### CODE REVIEW

**Comment by thulieblack** [comment]
Please resolve your conflicts first

**Comment by cybraia** [comment]
> Please resolve your conflicts first

Done it, please review. I am still working on "Browse all" button which opens a new page which has more photos.

**Comment by thulieblack** [comment]
Please resolve your conflicts @cybraia 

@Mayaleeeee please take a look

**Comment by akkshitgupta** [comment]
@thulieblack Isn't this a part of conference website maintenance under GSoC

**Comment by thulieblack** [comment]
No its not part of GSoC

**Pull request closed without merging**
