### PR TITLE
fix: open links in new tab of 'Resources Hub' section

### LINKED ISSUE #434: Links in the Resources Hub Should Open in a New Window
Currently, the links in the "Resources Hub" navigation menu open in the same window, which can interrupt the user's flow when navigating through the site. To improve user experience, these links should open in a new tab/window.

### PR DESCRIPTION
**Pull request by toffee-k21**
**Description**

- fixes #434 
- links will be opened in a new tab of 'Resources Hub'

### CODE REVIEW

**Review by AceTheCreator — CHANGES_REQUESTED** [review]
Quick one, i think you should pair the target with these rel attribute `rel="noopener noreferrer"` to avoid security risk

**Comment by toffee-k21** [comment]
> Quick one, i think you should pair the target with these rel attribute `rel="noopener noreferrer"` to avoid security risk

Done

**Review by AceTheCreator — APPROVED** [review]
LGTM!

**Pull request merged**
