### PR TITLE
fix: existing lint issues

### LINKED ISSUE #328: [FEATURE] Resolve the existing Next.js lint issues
### Why do we need this improvement?

To improve the lint flow of the website and put proper checks in place.

**`NOTE`: **This is a breaking change hence, when you work on this make sure to not dirupt the functionality****

### How will this change help?

It will make better use of Next.js components and hence improve in website performance.

### Screenshots

Screenshot from 2024-04-09 10-50-05

### How could it be implemented/designed?

1. Lint the code using the `npm run lint` command. 
2. Resolve the warnings that occur in the terminal.
3. Resources to follow  https://nextjs.org/docs

### 🚧 Breaking changes

Yes

### 👀 Have you checked for similar open issues?

- [X] I checked and didn't find a similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/asyncapi/.github/blob/master/CONTRIBUTING.md)

### Are you willing to work on this issue?

No, someone else can work on it.

### Suppoerted issues

https://github.com/asyncapi/conference-website/issues/306

### Supported PR

https://github.com/asyncapi/conference-website/pull/307

### PR DESCRIPTION
**Pull request by kavania2002**
**Description**

- Changed from `` to `<Image>` (used computed values for width/height if not given)
- Added dependencies in `useEffect` function

**Related issue(s)**
Fixes #328

### CODE REVIEW

**Comment by ashmit-coder** [comment]
Hey @kavania2002 please look into this

**Review by ashmit-coder — APPROVED** [review]
LGTM!

**Comment by AceTheCreator** [comment]
@kavania2002 can you resolve the merge conflict?

**Pull request merged**
