### PR TITLE
feat: add conference recordings to Online venue

### PR DESCRIPTION
**Pull request by Manancode**
Added conference recording playlist configuration to the Online venue to make sessions easily accessible to attendees directly from the venue page
Added recordings and playlist URLs to Online venue configuration in city-lists.json

Before:
scrnli_IvKh07LAp3CXSx

After:
scrnli_0AYXn26ty4t394
scrnli_6K43Z0sGS4sZ1J

fixes [issue](https://github.com/asyncapi/conference-website/issues/452#issue-2630012422)

### CODE REVIEW

**Comment by thulieblack** [comment]
More videos is a feature from YouTube @Mayaleeeee. 

The playlist is embedded correctly from my perspective

**Comment by ashmit-coder** [comment]
> More videos is a feature from YouTube @Mayaleeeee.
> 
> The playlist is embedded correctly from my perspective

LGTM as well @Mayaleeeee .

**Comment by Mayaleeeee** [comment]
> More videos is a feature from YouTube @Mayaleeeee. 
> 
> The playlist is embedded correctly from my perspective

Ahh, I see.

The pr looks good then.

**Review by Mayaleeeee — APPROVED** [review]

**Review by ashmit-coder — APPROVED** [review]

**Comment by ashmit-coder** [comment]
Merging!

**Pull request merged**
