### PR TITLE
fix: fixed apply as a speaker button in Paris Conference page

### LINKED ISSUE #179: Paris Conference - Apply as a Speaker don't work
#### Describe the bug

Paris Conference - Apply as a Speaker doesn't work. IDK if that is because it is not working, or stopped working.
https://conference.asyncapi.com/venue/Paris#sponsors

#### How to Reproduce
Steps to reproduce the issue. Attach all resources that can help us understand the issue:

Screenshot 2023-08-31 at 14 14 52

### PR DESCRIPTION
**Pull request by ankur0904**
**Description**

Fixed the `Apply as a Speaker` button to work as expected.

**Related issue(s)**
Fixes #179 

cc @AceTheCreator @thulieblack

### CODE REVIEW

**Comment by AceTheCreator** [comment]
@ankur0904, the link should only be applied for Paris(it also includes Bangalore). It should also be included in the venue section :)

**Comment by thulieblack** [comment]
The Apply button is not working from my end


[screen-capture.webm](https://github.com/asyncapi/conference-website/assets/66913810/306e84e3-9f93-4a43-89fd-8effd54c7475)

**Comment by ankur0904** [comment]
@AceTheCreator @thulieblack Made the required changes.

**Comment by thulieblack** [comment]
console.log shouldn't be visible

image

**Comment by ankur0904** [comment]
@thulieblack Removed `console.log`

**Comment by thulieblack** [comment]
Perfect, I will merge this next week together #184

**Comment by ankur0904** [comment]
@AceTheCreator Done :)

**Comment by AceTheCreator** [comment]
@ankur0904 you have some build error :)

**Comment by ankur0904** [comment]
@AceTheCreator Fixed :)

**Pull request merged**
