### PR TITLE
feat: update ticket cards

### PR DESCRIPTION
**Pull request by thulieblack**
update ticket cards and redirection

### CODE REVIEW

**Comment by thulieblack** [comment]
@AceTheCreator

**Comment by AceTheCreator** [comment]
> ### 👷 Deploy Preview for _peaceful-ramanujan-288045_ processing.
> Name	Link
> 🔨 Latest commit	[ddb7d94](https://github.com/asyncapi/conference-website/commit/ddb7d94db809d915d12a2ac522469efede7b70b8)
> 🔍 Latest deploy log	https://app.netlify.com/sites/peaceful-ramanujan-288045/deploys/66c6254bf84c460008fa43ce

@thulieblack i think we should add the shadow effect on Hover. wyt?

**Comment by thulieblack** [comment]
@AceTheCreator I am not a CSS expect, so here's the thing:

I want to ensure that tickets for past events are not visible, and when the ticket limit has been reached, we should remove the card. But now there is a huge space in between the card; how do we fix this

**Comment by AceTheCreator** [comment]
> @AceTheCreator I am not a CSS expect, so here's the thing:
> 
> I want to ensure that tickets for past events are not visible, and when the ticket limit has been reached, we should remove the card. But now there is a huge space in between the card; how do we fix this
> 
> image

This will require you to implement some js logic, by comparing the event date with the current date and decide what show based on the result.

**Comment by AceTheCreator** [comment]
If you want, i can help contribute to that directly to your PR

**Comment by thulieblack** [comment]
Okay cool you can

**Comment by AceTheCreator** [comment]
wyt @thulieblack?

**Comment by thulieblack** [comment]
looks awesome but lets make the London card ticket visible because people might think it's not active without hovering over

**Comment by thulieblack** [comment]
@AceTheCreator all good now

**Pull request merged**
