### PR TITLE
feat: add all speakers button

### PR DESCRIPTION
**Pull request by Sylvie-Wxr**
Add all speakers button

solves https://github.com/asyncapi/conference-website/issues/163

image

image

### CODE REVIEW

**Comment by AceTheCreator** [comment]
Nicely done @Sylvie-Wxr 

Just a few changes are needed.

- On the desktop view, there needs to be spacing between the buttons
- On the mobile view, the active nav background color needs to be the gradient color

**Comment by Sylvie-Wxr** [comment]
Hey @AceTheCreator, should we do the following in a separate issue/PR and merge this first?

> On the mobile view, the active nav background color needs to be the gradient color

**Comment by AceTheCreator** [comment]
@Sylvie-Wxr you can do it on the same PR

**Comment by Sylvie-Wxr** [comment]
Hi @AceTheCreator , is this the color you meant? 

image

**Comment by AceTheCreator** [comment]
@Sylvie-Wxr, what I mean is the Button itself should be colored :)

**Comment by Sylvie-Wxr** [comment]
image

@AceTheCreator Like this?

**Comment by AceTheCreator** [comment]
Yea @Sylvie-Wxr Also you should also include color on the border :)

**Comment by AceTheCreator** [comment]
LGTM!!!

**Pull request merged**
