### PR TITLE
fix: content aligned in mobile view

### PR DESCRIPTION
**Pull request by Aryan4884**
#345 
This PR addresses the issue of text alignment within the Dropdown component. Previously, the text was left-aligned on smaller screens, which affected the overall user experience. 

Changes Made:
Previously: <div>{active}</div> {/* Center the button text */}
After Change: <div className="flex-grow text-center">{active}</div> {/* Center the button text */}

Previously:
Screenshot 2024-10-03 114349
After change:
Screenshot 2024-10-03 114506

### CODE REVIEW

**Comment by ashmit-coder** [comment]
Hey @Aryan4884 could you please include the screenshots of the changes that you have made.

**Comment by Aryan4884** [comment]
Done

**Review by AceTheCreator — COMMENTED** [review]
@Aryan4884 i honestly don't see a reason for this enhancement cuz it works perfectly and the only suggested improvement is the arrow rotation and color, don't you think? 🤷🏽‍♂️

**Comment by Aryan4884** [comment]
@AceTheCreator Yes, it works perfectly fine.But the aligned text in the mobile view just looks better somwhow.

**Comment by ashmit-coder** [comment]
> @Aryan4884 i honestly don't see a reason for this enhancement cuz it works perfectly and the only suggested improvement is the arrow rotation and color, don't you think? 🤷🏽‍♂️

So are we moving ahead with these changes?

**Comment by AceTheCreator** [comment]
> @AceTheCreator Yes, it works perfectly fine.But the aligned text in the mobile view just looks better somehow.

Hmm... I beg to differ 

@Mayaleeeee your thoughts?

**Review by Mayaleeeee — COMMENTED** [review]
What we have on the website looks great.👌👍

We don't need these changes.

cc @ashmit-coder @AceTheCreator

**Comment by AceTheCreator** [comment]
@Aryan4884 i'm closing this PR :/

**Pull request closed without merging**
