### PR TITLE
feat: made prospectus downloadable

### PR DESCRIPTION
**Pull request by ashmit-coder**
**Description**

- Added the current Prospectus PDF and made it downloadable.

**Related issue(s)**

Resolves: #329

### CODE REVIEW

**Review by AceTheCreator — COMMENTED** [review]
Do you mind adding a download icon in the button to make users know that it's a download button?

**Comment by ashmit-coder** [comment]
> Do you mind adding a download icon in the button to make users know that it's a download button?

Sure I can!
Just what icon should I use could you suggest that

**Comment by ashmit-coder** [comment]
> > Do you mind adding a download icon in the button to make users know that it's a download button?
> 
> Sure I can! Just what icon should I use could you suggest that

In my opinion one of these should be fine https://react-icons.github.io/react-icons/search/#q=download

**Comment by AceTheCreator** [comment]
> > > Do you mind adding a download icon in the button to make users know that it's a download button?
> > 
> > 
> > Sure I can! Just what icon should I use could you suggest that
> 
> In my opinion one of these should be fine https://react-icons.github.io/react-icons/search/#q=download

Hmmm... do we really have to install an icon library?

**Comment by AceTheCreator** [comment]
You can just do it the way it's been done already

**Comment by ashmit-coder** [comment]
> You can just do it the way it's been done already

No I mean just suggest a icon from that page I will implement the way we do it :sweat_smile:

**Comment by ashmit-coder** [comment]
> Contributor

Hey @AceTheCreator or @thulieblack , could you suggest something over this?

**Comment by thulieblack** [comment]
Not sure what @AceTheCreator meant by the download icon.

Maybe specify on the Button text that -Download Sponsorship Prospectus

image

**Comment by ashmit-coder** [comment]
> Not sure what @AceTheCreator meant by the download icon.
> 
> Maybe specify on the Button text that -Download Sponsorship Prospectus
> 
> image

He meant the same thing, just instead of `Download` in text we use a download icon

**Comment by thulieblack** [comment]
Can't you embed the icon on the button?

**Comment by ashmit-coder** [comment]
> Can't you embed the icon on the button?
> 
> image

Yeah thats exactly what we where thinking, :sweat_smile: .

Just the doubt was whay icon will go properly with the theme.

Hence I suggested using https://react-icons.github.io/react-icons/search/#q=download
One of the in the url in Image format ( the usual way in the site)

**Comment by thulieblack** [comment]
lets try that and see how it;ll look

**Review by AceTheCreator — APPROVED** [review]
LGTM!

**Pull request merged**
