### PR TITLE
feat: include a map section on each venue page

### LINKED ISSUE #165: Include a map section on each venue page
The current implementation of the venue pages needs a map section indicating the venue's location.

AACoT-–-Figma

Link to design https://www.figma.com/file/sS5ofLRtuFqDGFvlNBurns/AACoT?type=design&node-id=0-1&mode=design&t=twZEjRCAZ0i1nP5b-0

### PR DESCRIPTION
**Pull request by kabszac**
**Description**

- Added  a map section on each page 
- I used leaflet and react - leaflet
- This fixes #165 

Screenshot from 2023-08-24 11-55-28
Screenshot from 2023-08-24 11-55-37

### CODE REVIEW

**Comment by AceTheCreator** [comment]
Looks good! Just a minor suggestion: can you reduce the height of the map a bit?

**Comment by kabszac** [comment]
@AceTheCreator  what suggestion would you have the ideal height to be?

**Comment by AceTheCreator** [comment]
> @AceTheCreator what suggestion would you have the ideal height to be?

I mean probably half of the current view we have now @kabszac

**Comment by kabszac** [comment]
@AceTheCreator thank you let me make the necessary changes

**Comment by AceTheCreator** [comment]
@kabszac any update on this?

**Comment by kabszac** [comment]
@AceTheCreator made the changes

**Comment by AceTheCreator** [comment]
@kabszac you have a merge conflict :)

**Comment by kabszac** [comment]
@AceTheCreator resolved the merge conflict

**Comment by kabszac** [comment]
@AceTheCreator resolved

**Comment by kabszac** [comment]
@AceTheCreator let me try opening another request on this issue

**Comment by AceTheCreator** [comment]
> @AceTheCreator let me try opening another pull request on this issue. is it ok?

Okay

**Pull request closed without merging**
