### PR TITLE
fix: #356,  Added hover effects to navbar and buttons

### PR DESCRIPTION
**Pull request by SagarSharma2809**
**Description**

- Added Subtle hover effects to navbar and button Component.

After:

https://github.com/user-attachments/assets/c54db47f-dfb2-4cf6-9e2f-aacbc12a4af5

**Related issue(s)**
Fixes issue #356

### CODE REVIEW

**Comment by SagarSharma2809** [comment]
Hi @Mayaleeeee, 
I haven't done extreme effects to stay aligned with the website theme. Please set me know if there is anything you want to add to it.

**Comment by chaitanyakatore** [comment]
@SagarSharma2809 your all test cases are not passing you should edit the title of your PR to small letter instead of capital one

**Review by Mayaleeeee — COMMENTED** [review]
Looks good! 
Thank you


Thoughts? @AceTheCreator @ashmit-coder @thulieblack

**Comment by SagarSharma2809** [comment]
> @SagarSharma2809, looks good to me ❤️
> 
> Can you resolve the conflict?

Thank you! I noticed the website now has new hover effects on buttons. Would you still like to use the hover effects from my PR, or would you prefer to keep the current ones? I feel the existing ones might be more effective.

Please let me know!

**Comment by AceTheCreator** [comment]
@SagarSharma2809 thanks for your awesome contribution. I'll kindly go ahead and close this PR. 

Feel free to suggest other enhancements.

**Pull request closed without merging**
