### PR TITLE
fix: fixed the submenu not Closing when click

### PR DESCRIPTION
**Pull request by TenzDelek**
fix: #316 

- changed the click to hover similar to the main website
-before:
https://github.com/asyncapi/conference-website/assets/122612557/de07b13e-7266-4038-ae9e-672fbe14e4bb
-after:
https://github.com/asyncapi/conference-website/assets/122612557/e546009b-1545-4b43-81a7-dedc1676ab25

### CODE REVIEW

**Review by Mayaleeeee — APPROVED** [review]
This looks good. Thank you @TenzDelek

**Comment by thulieblack** [comment]
@AceTheCreator can you have a look here

**Review by AceTheCreator — APPROVED** [review]
LGTM!

**Pull request merged**
