### PR TITLE
feat: add paris details

### PR DESCRIPTION
**Pull request by thulieblack**
Start adding details for the Paris conference page
solves #190

### CODE REVIEW

**Comment by thulieblack** [comment]
cc @AceTheCreator

**Comment by AceTheCreator** [comment]
> cc @AceTheCreator

Nice! It would be best if you increased the width of the button. 
deploy-preview-184-peaceful-ramanujan-288045-netlify-app-venue-Bangalore

**Comment by thulieblack** [comment]
yo @AceTheCreator I need help with adding the link to the cfp form

**Comment by thulieblack** [comment]
yo @AceTheCreator please merge

**Comment by AceTheCreator** [comment]
> yo @AceTheCreator please merge

LGTM!

**Pull request merged**
