### PR TITLE
fix: update get free tickets button

### LINKED ISSUE #198: Update `Get Free Tickets` on main page to link to proper google form
Tickets button in https://conference.asyncapi.com/ leads to London tickets. IMHO we should promote Madrid conf there -> https://docs.google.com/forms/d/e/1FAIpQLSdwqi27LpsIi8tKQoQBcUWDUJZi0be0cHpWnDtWhhHVn00hFA/viewform

Suggested changes:
- button should link to https://docs.google.com/forms/d/e/1FAIpQLSdwqi27LpsIi8tKQoQBcUWDUJZi0be0cHpWnDtWhhHVn00hFA/viewform
- maybe button tex should somehow suggest what edition it is related to? like `Get Free Tickets` should be `Get Free Tickets for Madrid` or basically below `Get Free Tickets` it should say `Madrid`, smaller cases

### PR DESCRIPTION
**Pull request by SoNiC-HeRE**
**Description**

- Google Form is already updated  as requested in #198
- Changed the Get Ticket Button to show Madrid Location as requested in #198

Before:
image

After:
Screenshot from 2023-09-30 09-56-00

**Related issue(s)**
Fixes #198

### CODE REVIEW

**Comment by Mayaleeeee** [comment]
Thank you, @SoNiC-HeRE for your effort! To ensure consistency with our other pages, let's use '**Free Tickets for Madrid**' in a horizontal layout, without placing 'Madrid' beneath 'Get Free Tickets for Madrid.'

**Comment by SoNiC-HeRE** [comment]
> Thank you, @SoNiC-HeRE for your effort! To ensure consistency with our other pages, let's use '**Free Tickets for Madrid**' in a horizontal layout, without placing 'Madrid' beneath 'Get Free Tickets for Madrid.'
> 
> cc @derberg @AceTheCreator @thulieblack

Sure I'll change it,I was following what was mentioned here #198

**Comment by SoNiC-HeRE** [comment]
image

**Comment by SoNiC-HeRE** [comment]
@Mayaleeeee please let me know if further changes are required

**Comment by Mayaleeeee** [comment]
> @Mayaleeeee please let me know if further changes are required

We don't need to add a colon, just this 👇👇👇

**Free Tickets for Madrid**

**Comment by SoNiC-HeRE** [comment]
image

**Comment by Mayaleeeee** [comment]
> image
> 
> @Mayaleeeee

Remove the ''Get'' 

''**Free Tickets For Madrid**" is fine.

**Comment by SoNiC-HeRE** [comment]
> > image
> > @Mayaleeeee
> 
> Remove the ''Get''
> 
> ''**Free Tickets For Madrid**" is fine.

I've applied the changes, let me know if anything else needs to be done

**Comment by Mayaleeeee** [comment]
> > > image
> > > @Mayaleeeee
> > 
> > Remove the ''Get''
> > 
> > ''**Free Tickets For Madrid**" is fine.
> 
> I've applied the changes, let me know if anything else needs to be done
> 
> image
> 


Awesome 🎉🎉
Thank you @SoNiC-HeRE

**Comment by AceTheCreator** [comment]
@SoNiC-HeRE update the Madrid ticket link to this https://www.eventbrite.es/e/entradas-asyncapi-conf-on-tour-2023-735378636297 and resolve the conflicts in your PR and we are good to go :)

**Comment by SoNiC-HeRE** [comment]
> @SoNiC-HeRE update the Madrid ticket link to this https://www.eventbrite.es/e/entradas-asyncapi-conf-on-tour-2023-735378636297 and resolve the conflicts in your PR and we are good to go :) 

Sure, I'll get this fixed

**Comment by AceTheCreator** [comment]
Sorry, I have to close this PR as the enhancement is not needed anymore due to an updated version of the website :)

**Pull request closed without merging**
