### PR TITLE
fix: description of Tickets Sale and Event and Host Sponsor is not visible

### LINKED ISSUE #302: [BUG]: Description of Tickets Sale and Event and Host Sponsor is not visible.
### Describe the bug.

Hello @
Description of Tickets Sale and Event and Host Sponsor is not visible in between 700px to 590px. you can check 

### Expected behavior

Description of Tickets Sale and Event and Host Sponsor is  visible completely in between 700px to 590px. you can check 

### Screenshots

before 
Screenshot 2024-04-05 105451
Screenshot 2024-04-05 105439

after
Screenshot 2024-04-05 114457
Screenshot 2024-04-05 114447

### How to Reproduce

1. first check with all pixels
2. add new class of width style 

### 🥦 Browser

Microsoft Edge

### 👀 Have you checked for similar open issues?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/asyncapi/.github/blob/master/CONTRIBUTING.md)

### Are you willing to work on this issue ?

Yes I am willing to submit a PR!

### PR DESCRIPTION
**Pull request by techmannih**
Issue #302 
close #302 

**Description**
[Fix:](fix:Description of Tickets Sale and Event and Host Sponsor is not visible)
Screenshot 2024-04-05 114447
Screenshot 2024-04-05 114457

### CODE REVIEW

**Comment by akkshitgupta** [comment]
Kindly follow the pull request conventions suggested here: https://github.com/asyncapi/conference-website/pull/303#issuecomment-2039033730
also don't include the `package-lock.json` file in this pull request :)

**Comment by techmannih** [comment]
this is not added in .gitignore file.

**Comment by AceTheCreator** [comment]
@techmannih can you get rid of the changes in the package.lock file?

**Comment by techmannih** [comment]
@AceTheCreator can you check now please

**Review by AceTheCreator — APPROVED** [review]
LGTM!

**Pull request merged**
