### PR TITLE
fix: added width to SVG

### PR DESCRIPTION
**Pull request by akshatnema**
This PR targets to add the width on the SVG (Patterns) to correct the view of the website in the FIrefox browser.

**Note:** Please ignore the slight change in the width of the Patterns as the width classes of the Tailwind are added to the Patterns.

### CODE REVIEW

**Comment by akshatnema** [comment]
@derberg Kindly see the preview of the deployed changes and review the PR.

**Comment by AceTheCreator** [comment]
> @derberg Kindly see the preview of the deployed changes and review the PR.

@akshatnema Thanks for the quick fix, that was awesome!

**Comment by akshatnema** [comment]
Does this PR don't require an approval review?

**Review by derberg — APPROVED** [review]

**Pull request merged**
