### PR TITLE
fix: fixed runtime error that occurs because, classList reading properties of null

### PR DESCRIPTION
**Pull request by Vibgitcode27**
**Description**

- There is Unhandled Runtime Error that pops up . This happens beacause we are trying to access the classList property of a DOM element that is null at the time of access.

**Related issue(s)**

Solves issue #215

### CODE REVIEW

**Comment by Vibgitcode27** [comment]
Kindly add label for hacktoberfest. Thank you.

**Comment by AceTheCreator** [comment]
@Vibgitcode27, please remove the .idea folder included in the PR

**Comment by Vibgitcode27** [comment]
> @Vibgitcode27, please remove the .idea folder included in the PR

Done 👍

**Comment by AceTheCreator** [comment]
@Vibgitcode27 left some reviews for you :)

**Comment by Vibgitcode27** [comment]
> @Vibgitcode27 left some reviews for you :)

Thanks @AceTheCreator . I can't find any reviews in the file change log. Is there something else you want to communicate?

**Comment by AceTheCreator** [comment]
> > @Vibgitcode27 left some reviews for you :)
> 
> Thanks @AceTheCreator . I can't find any reviews in the file change log. Is there something else you want to communicate?

What do you mean?

**Comment by Vibgitcode27** [comment]
> > > @Vibgitcode27 left some reviews for you :)
> > 
> > 
> > Thanks @AceTheCreator . I can't find any reviews in the file change log. Is there something else you want to communicate?
> 
> What do you mean?

I can't see any reviews @AceTheCreator . Will you merge this pull request?

**Comment by AceTheCreator** [comment]
@Vibgitcode27 You need to add the suggested changes :)

**Comment by Vibgitcode27** [comment]
> @Vibgitcode27, please remove the .idea folder included in the PR

@AceTheCreator  here you suggested to remove .idea I did that in newer commit. I don't understand what other changes you want me to do.

**Comment by AceTheCreator** [comment]
> > @Vibgitcode27, please remove the .idea folder included in the PR
> 
> @AceTheCreator here you suggested to remove .idea folder I did that in newer commit. I don't understand what other changes you want me to do.

Do you see this section? 

fix-fixed-runtime-error-that-occurs-because-classList-reading-properties-of-null-by-Vibgitcode27-·-Pull-Request-218-·-asyncapi-conference-website

**Comment by Vibgitcode27** [comment]
> > > @Vibgitcode27, please remove the .idea folder included in the PR
> > 
> > 
> > @AceTheCreator here you suggested to remove .idea folder I did that in newer commit. I don't understand what other changes you want me to do.
> 
> Do you see this section?
> 
> fix-fixed-runtime-error-that-occurs-because-classList-reading-properties-of-null-by-Vibgitcode27-·-Pull-Request-218-·-asyncapi-conference-website
Screenshot 2023-10-13 231519

Sorry for bothering you that much @AceTheCreator. I genuinely can't see you reviews ! But I have commited changes what I could figure out throught you screenshots
Screenshot 2023-10-13 231452

**Review by AceTheCreator — APPROVED** [review]

**Comment by AceTheCreator** [comment]
@Vibgitcode27 it's fine :) Everything LGTM! 👍🏾

**Comment by Vibgitcode27** [comment]
> @Vibgitcode27 it's fine :) Everything LGTM! 👍🏾

@AceTheCreator  Thank you @AceTheCreator . I would be glad if you could add hacktober labels for this PR.

**Comment by AceTheCreator** [comment]
> > @Vibgitcode27 it's fine :) Everything LGTM! 👍🏾
> 
> @AceTheCreator Thank you @AceTheCreator . I would be glad if you could add hacktober labels for this PR.

@Vibgitcode27 I don't think that'll be necessary cuz the issue and repo already have the label :)

**Pull request merged**
