### PR TITLE
fix: update speakers.json

### PR DESCRIPTION
**Pull request by ivangsa**
Remove Alexis Sanchez from Speakers list and add back Alejandra Quetzalli

I added back the two breaks in the afternoon.

### CODE REVIEW

**Comment by thulieblack** [comment]
yo @AceTheCreator can you remove Alex Sanchez from speakers and merge please

**Comment by AceTheCreator** [comment]
@ivangsa can you also remove Alexis info in the speakers object?

**Comment by ivangsa** [comment]
removed

**Comment by ivangsa** [comment]
@AceTheCreator @thulieblack Can you review and merge this rescheduling?

**Pull request merged**
