### PR TITLE
feat: designismypassion

### PR DESCRIPTION
**Pull request by derberg**

### CODE REVIEW

**Comment by mcturco** [comment]
ANXIETY 😆

**Comment by derberg** [comment]
@mcturco you see, you can't leave us alone. In Poland we have a saying "gdy kota nie ma to myszy charcują" which means `when the cat's away the mice will play` 😈

**Comment by fmvilas** [comment]
We should implement some kind of punishment/fines system for this kind of PRs 😂

**Comment by magicmatatjahu** [comment]
@derberg without jokes 😆 Is it possible to somehow hide this div and expand it with the "Show more" button or enable scrolling in the smaller div? It currently stretches page in a messy way. If you want I can try to figure it out.

**Comment by mcturco** [comment]
I hate to continually hate on this app, but the developers really did just spend all their time making this:

Screen Shot 2022-09-21 at 9 14 01 AM

My opinions:
I don't think the background of it should be the violet color, I think we can just add a white section to the website and slap it in there, considering there's nothing else really that we can do about it. Maybe we can also put this on its own page, that way it wouldn't make the landing page seem like it is scrolling forever, and we can just add a call to action on the landing page to be taken to the schedule page

**Comment by derberg** [comment]
closing as @AceTheCreator is doing a lot of progress in https://github.com/asyncapi/conference-website/pull/102 already 💪🏼

**Pull request closed without merging**
