### PR TITLE
fix: dom issue

### PR DESCRIPTION
**Pull request by arpitkuriyal**
**Description**

- fix: solve the issue of DOM property warning 

**Related issue(s)** #439

### CODE REVIEW

**Comment by arpitkuriyal** [comment]
@AceTheCreator  can you please review it.

**Comment by toffee-k21** [comment]
Hey @arpitkuriyal, I noticed you made changes to the CSS, but that wasn't part of the issue requirements. Could you please adjust it to keep the scope focused on the issue's specific needs?

**Comment by arpitkuriyal** [comment]
@toffee-k21  okay i will make changes

**Review by AceTheCreator — CHANGES_REQUESTED** [review]
Please remove the package.lock changes 🙏🏽

**Comment by arpitkuriyal** [comment]
@AceTheCreator  Sorry for the changes. I have reverted the changes in the package-lock.json file

**Review by AceTheCreator — APPROVED** [review]
LGTM!

**Pull request merged**
