### PR TITLE
feat: added a mapsection on each venue page

### LINKED ISSUE #165: Include a map section on each venue page
The current implementation of the venue pages needs a map section indicating the venue's location.

AACoT-–-Figma

Link to design https://www.figma.com/file/sS5ofLRtuFqDGFvlNBurns/AACoT?type=design&node-id=0-1&mode=design&t=twZEjRCAZ0i1nP5b-0

### PR DESCRIPTION
**Pull request by kabszac**
**Description**

- Added a map section on each venue page
- I used leaflet and react - leaflet

**Related issue(s)**
fixes #165 

Screenshot from 2023-09-30 00-46-35

Screenshot from 2023-09-30 00-46-41

### CODE REVIEW

**Comment by kabszac** [comment]
@AceTheCreator made a new pull request kindly review.

**Comment by AceTheCreator** [comment]
> @AceTheCreator made a new pull request kindly review.

LGTM!

**Comment by AceTheCreator** [comment]
@Mayaleeeee wyt?

**Comment by Mayaleeeee** [comment]
> @Mayaleeeee wyt?

Looks good, thanks @kabszac.

Here are my observations @kabszac :

1. The colour you used for the card is dark, compared to the one I used; please kindly use the one in the image I sent below.
2. The spacing between the location is too much as well, please kindly reduce it and make them both aligned in the center.
Screenshot 2023-10-05 115318
cc @AceTheCreator 

Below is the image for reference
Map

**Comment by kabszac** [comment]
@Mayaleeeee made the changes.

**Comment by AceTheCreator** [comment]
> @Mayaleeeee made the changes.

cc @Mayaleeeee

**Comment by Mayaleeeee** [comment]
> > @Mayaleeeee made the changes.
> 
> cc @Mayaleeeee 

Thanks @kabszac @AceTheCreator 

I can only see this on my phone, and I'm not sure why the location pointer is white. Additionally, I couldn't find the card that displays the description.

Regardless, I'll take another look when I'm on my laptop.

**Comment by Mayaleeeee** [comment]
> > @Mayaleeeee made the changes.
> 
> cc @Mayaleeeee

@kabszac, thank you for working on this; here are my reviews on the design.

1. The location pointer need not be clicked to view the placeholder. The purpose of the placeholder is to provide the user with a glance at the location and date. Therefore, there is no need for any interaction with the card, as seen in the recording below.
[23082528-6867-4f0a-8dd0-7c0ed2521392.webm](https://github.com/asyncapi/conference-website/assets/105395613/378c823e-7e5c-41b9-a4b9-478183ae35e2)


2. The location icon on the card is too small compared to the calendar icon. I used 20px for the icons and 16px for the texts.
Screenshot 2023-10-11 022115


3. Instead of being placed outside, The 'X' close icon should be positioned inside the card at the top with a white colour. The expected design is shown in the image below. When the user clicks on the 'X' icon, it should close the card, and the card should reopen when the user clicks on the location pointer.

Screenshot 2023-10-11 024410

**Comment by thulieblack** [comment]
Website has been updated to 2024

**Pull request closed without merging**
