### PR TITLE
feat: remove registration and add links to streams

### PR DESCRIPTION
**Pull request by derberg**
We should display in one place link to all the accounts where live stream will be available.

Opened for suggestions how to improve it. I can even close this PR in favour of something different.

My only strong opinion is that these should be links and not embedded video for example from YouTube as taking users to the specific platform to our account could convert into a "follow"

I also added info about winners of the hackathon

### CODE REVIEW

**Comment by magicmatatjahu** [comment]
image

Is it an optical illusion or is the Youtube button bigger than the others?

**Comment by derberg** [comment]
@magicmatatjahu I'm not good to ask about optical things, lgtm 😄 I wanted to make a small space between each but I'm too dumb to do it.

Yes, eventually would be great to update links every day to actual streams. This would be the ultimate goal. But we cannot wait until tomorrow with this PR as we should not allow any more registrations as soon I will send an email to all registrants

**Review by fmvilas — APPROVED** [review]

**Review by magicmatatjahu — APPROVED** [review]
> Yes, eventually would be great to update links every day to actual streams. This would be the ultimate goal. But we cannot wait until tomorrow with this PR as we should not allow any more registrations as soon I will send an email to all registrants

Ok then, we should remember about links :)

**Comment by derberg** [comment]
@magicmatatjahu yup, will count on you 😉 like if I see there is to much around I will send links to you or even ask you to pick them up 🙇🏼

**Comment by derberg** [comment]
Screenshot 2021-11-15 at 19 07 41

@fmvilas @magicmatatjahu added link to slack

**Comment by derberg** [comment]
I'm merging, any fixes must go as followups, I just need to block registrations now

**Comment by fmvilas** [comment]
Shipt it and keep iterating on further PRs, if needed. The earlier we have this the better.

**Pull request merged**
