### PR TITLE
feat: add YT livestream preview

### PR DESCRIPTION
**Pull request by magicmatatjahu**
**Description**

Added conference banner with YT livestream - like in https://github.com/asyncapi/website/pull/1070

cc @derberg @AceTheCreator 

Example:

image

### CODE REVIEW

**Comment by AceTheCreator** [comment]
@magicmatatjahu I noticed your changes is not reflecting in the deploy preview link

**Comment by magicmatatjahu** [comment]
@AceTheCreator that's the plan :) https://github.com/asyncapi/conference-website/pull/121/files#diff-6c4119a86718dc9798cd5e3f2971d9bf4da29daab1e5eeee2412ea5defb44bd0R40 It will be showed only 3-5 November UTC.

**Comment by AceTheCreator** [comment]
> @AceTheCreator that's the plan :) https://github.com/asyncapi/conference-website/pull/121/files#diff-6c4119a86718dc9798cd5e3f2971d9bf4da29daab1e5eeee2412ea5defb44bd0R40 It will be showed only 3-5 November UTC.

Haha I see :)

**Comment by derberg** [comment]
@AceTheCreator you have to change system settings, move into future and then you can see it in the preview.

@magicmatatjahu can you remove registration link, it is not needed. And add "chat" reference?

**Comment by magicmatatjahu** [comment]
@derberg No problem, I will do, but I have a problem with this header:

> A Virtual Tech Conference
> Nov 3-5 * Online via live stream

Should we write something like:

> A Virtual Tech Conference
> Nov 3-5 * Online via live stream, Day 1 is running

wdyt?

**Comment by derberg** [comment]
@magicmatatjahu makes sense 👍🏼

**Comment by magicmatatjahu** [comment]
@derberg Done.

image

**Review by derberg — APPROVED** [review]
❤️

**Pull request merged**
