### PR TITLE
fix: redirection Link fix

### LINKED ISSUE #466: [BUG] Online Conference redirection on invalid link (youtube)
### Describe the bug.

as per the title

### Expected behavior

should redirect to the youtube live link

### Screenshots

image

### How to Reproduce

1. go to online conference
2. click on youtube link

### 🥦 Browser

Brave

### 👀 Have you checked for similar open issues?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/asyncapi/.github/blob/master/CONTRIBUTING.md)

### Are you willing to work on this issue ?

Yes I am willing to submit a PR!

### PR DESCRIPTION
**Pull request by TenzDelek**
**Description**
fixed the youtube redirection link
**Related issue(s)**

Fixes #466

### CODE REVIEW

**Review by AceTheCreator — CHANGES_REQUESTED** [review]
@tenzdelek, i noticed were the link is been referenced is not a button but a text, which can easily be missed. since the text is a link, then i believed it should be underlined. wyt @ashmit-coder?

**Comment by TenzDelek** [comment]
> @TenzDelek, i noticed were the link is been referenced is not a button but a text, which can easily be missed. since the text is a link, then i believed it should be underlined. wyt @ashmit-coder?

agree on that, currently, the underline is kept on hover. should I go on with the changes to add a underline?

**Review by ashmit-coder — APPROVED** [review]
LGTM!

**Comment by thulieblack** [comment]
Please link the text to the YouTube playlist https://youtube.com/playlist?list=PLbi1gRlP7pijItMBmw9SeeyWxuEa3jLR2&si=MNNU0r-aCmuWFPLI

**Comment by TenzDelek** [comment]
> Please link the text to the YouTube playlist https://youtube.com/playlist?list=PLbi1gRlP7pijItMBmw9SeeyWxuEa3jLR2&si=MNNU0r-aCmuWFPLI

done

**Comment by AceTheCreator** [comment]
> > @TenzDelek, i noticed were the link is been referenced is not a button but a text, which can easily be missed. since the text is a link, then i believed it should be underlined. wyt @ashmit-coder?
> 
> I dont think so @AceTheCreator , the underline seems to not go well with the design of the card, hence I dont think we should add it. The hover effect looks better and the text points towards it being a link.

Hmm... I actually missed that it was a link. Why not make it a button if adding an underline is gonna mess with the UI.

wyt @Mayaleeeee?

**Comment by TenzDelek** [comment]
image

https://conference.asyncapi.com/venue/Online

cc @Mayaleeeee

**Review by Mayaleeeee — COMMENTED** [review]
The text (that direct users to the YouTube recording) should be in a different colour (a bright colour because of the overlay background) and underlined.

cc @TenzDelek @AceTheCreator @ashmit-coder 

I think we can also use a button —since the online conference is different from the in-person ones.

**Review by AceTheCreator — APPROVED** [review]
LGTM!

**Comment by TenzDelek** [comment]
any changes are still needed here or are we ready to merge 🤔

**Comment by AceTheCreator** [comment]
@TenzDelek can you update this branch, so we can merge this PR?

**Comment by TenzDelek** [comment]
> @TenzDelek can you update this branch, so we can merge this PR?

done cc @AceTheCreator

**Review by AceTheCreator — APPROVED** [review]
LGTM!

**Pull request merged**
