### PR TITLE
fix: speakers images 

### PR DESCRIPTION
**Pull request by Aryan4884**
#396  
This PR resolves that issue by downloading and storing the speaker images locally. This change ensures that the speaker images are always available, thereby improving the overall reliability and consistency of the website.

Changes Made:
Speaker Images Storage:
Downloaded all speaker images from external URLs and stored them in the /public/img/speakers/ directory.
Updated the speaker image paths to reference the local files instead of external URLs.
Speaker Component:
Updated the image src in the Speaker component to use the new local paths.
Benefits:
Reliability: The images are no longer dependent on external URLs, preventing broken image issues caused by changes in external sources.
Performance: Local images reduce latency and improve load time, since they are served directly from our server.
Maintenance: Easier management of speaker images, as they are all stored and versioned within the project.
Screenshot 2024-10-01 175046

### CODE REVIEW

**Comment by Aryan4884** [comment]
Please ignore multiple commit as I have forgotten to make a different branch for this separate issue, thatswhy my previous commit which was for different issue are also getting shown.

**Comment by ashmit-coder** [comment]
Hey @Aryan4884 please follow the pr naming conventions as mentioned by the `asyncapi-bot ` above.

**Comment by Aryan4884** [comment]
Is it ok now?

**Review by AceTheCreator — CHANGES_REQUESTED** [review]
@Aryan4884 can you store all images in a .webp format?

**Comment by Aryan4884** [comment]
@AceTheCreator changed the format to .webp

**Comment by ashmit-coder** [comment]
@Aryan4884 there is some error, please resolve it. In my opinion its arising from the `conference-website` in your PR.

**Comment by Aryan4884** [comment]
@AceTheCreator By mistake i messed up the file directories and submodules.
But now its fine.

**Comment by ashmit-coder** [comment]
@Aryan4884 please resolve the merge conflicts.

**Comment by Aryan4884** [comment]
@ashmit-coder done

**Review by ashmit-coder — APPROVED** [review]
LGTM! @AceTheCreator

**Comment by Aryan4884** [comment]
@AceTheCreator done

**Review by AceTheCreator — APPROVED** [review]
LGTM!

**Pull request merged**
