### PR TITLE
fix: updated twitter icon and add hover effects to footer links

### LINKED ISSUE #223: update twitter icon and add interactions
#### Reason/Context
1. The current Twitter icon in the footer has become obsolete and should be replaced with a new "X" icon to align with the latest branding guidelines.

2. The footer lacks user interaction, with neither icons nor text responding to user actions, such as hover or click events.  

#### Description
 1. Update the Twitter icon in the footer to the new "X" icon and ensure the new icon maintains the website's visual consistency and branding.
 2. Implement hover and click interactions for icons and text in the footer. Icons and text elements like the "**Code of Conduct" and the "logo "** should provide visual feedback when users interact with them.

Screenshot 2023-10-13 115349

cc @AceTheCreator, please label it as an hacktoberfest issue.

### PR DESCRIPTION
**Pull request by MahendraDani**
**Description**

- Updated the twitter icon in footer to its new logo.
- Added hover effects to social links in the footer for better user experience.

**Outcomes**

https://github.com/asyncapi/conference-website/assets/116940083/6df84dc9-7a92-4fb5-b0cf-116b3e7608ce

**Related issue(s)**

Fixes #223

### CODE REVIEW

**Comment by MahendraDani** [comment]
@Mayaleeeee If there are any changes please let me know.

**Comment by AceTheCreator** [comment]
cc @Mayaleeeee

**Comment by Mayaleeeee** [comment]
I am on it.

**Comment by MahendraDani** [comment]
@Mayaleeeee do I need to update this branch with the `master` branch?

**Comment by Mayaleeeee** [comment]
> @Mayaleeeee do I need to update this branch with the `master` branch?

Yeah, I guess so.
cc @AceTheCreator

**Comment by AceTheCreator** [comment]
@MahendraDani did you remove the old twitter logo?

**Comment by MahendraDani** [comment]
@AceTheCreator I have removed the old twitter logo and used the new one.

**Comment by AceTheCreator** [comment]
> @AceTheCreator I have removed the old twitter logo and used the new one. But I have not deleted the `public/img/Twitter.png` which is the old twitter logo. Should I delete `public/img/Twitter.png` from the repo?

Yes, please delete it

**Comment by MahendraDani** [comment]
@AceTheCreator 
Deleted old tweeter logo from repo in https://github.com/asyncapi/conference-website/pull/225/commits/47e882f3db7facc9a32458b4d6aeae44349d2b65

**Comment by AceTheCreator** [comment]
LGTM!!! Well done @MahendraDani

**Comment by MahendraDani** [comment]
@AceTheCreator Thanks for merging the PR.
If there are any issues that I can help me please let me know.

**Pull request merged**
